### PR TITLE
NEW PR

### PR DESCRIPTION
**Pull request by mylegfeelsfunny**

### CODE REVIEW

**Comment by mylegfeelsfunny** [comment]
Test this please

**Comment by alonecuzzo** [comment]
PAL GIT THAT .GITIGNORE IN THAR AND GIT RID OF THAT .DS_STORE OMFG!

**Comment by alonecuzzo** [comment]
AND WE GOTTA CATCH UP THIS PAL JUST GOT FRIED FROM USTWO ON FRIDAY!!! FRIED!

**Comment by mylegfeelsfunny** [comment]
WAT!

> On Mar 13, 2017, at 10:29 AM, Jabari Bell <notifications@github.com> wrote:
> 
> AND WE GOTTA CATCH UP THIS PAL JUST GOT FRIED FROM USTWO ON FRIDAY!!! FRIED!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
 

Investment advisory services are offered by Collective Returns, Inc., dba 
Stash Invest, a federally-registered investment adviser. 

Stash's outgoing and incoming emails are electronically archived and 
subject to review and/or disclosure to someone other than the recipient. We 
cannot accept requests for securities transactions or other similar 
instructions through email. This communication is not an offer or 
solicitation to buy or sell any financial product(s). We cannot ensure the 
security of information emailed over the Internet, so you should be careful 
when transmitting confidential information such as account numbers and 
security holdings. If the reader of this message is not the intended 
recipient, or an employee or agent responsible for delivering this message 
to the intended recipient, you are hereby notified that any dissemination, 
distribution or copying of this communication is strictly prohibited. If 
you have received this communication in error, please notify us immediately 
by replying to this message and deleting it from your computer.

**Pull request closed without merging**
